name: Build and test the application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Unit test
        run: | 
          mvn -Dspring.profiles.active=test -Daam.github.repository=${{github.repository}} -Daam.github.token=${{secrets.AAM_GITHUB_TOKEN}} test

      - name: Build with Maven
        run: mvn package -DskipTests

      - uses: actions/upload-artifact@v3
        with:
          name: ActionAPIMonitor
          path: target/ActionAPIMonitor-1.0-SNAPSHOT.jar